name: CI

on:
  push:
    branches:
      - main
    tags: [ 'v*' ]
  pull_request:
    branches:
      - main

jobs:

  lint:
    name: Linter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install itself
      run: |
        python setup.py install
    - name: Run linters
      run: |
        make lint
    - name: Install spell checker
      run: |
        sudo apt install libenchant-dev
        pip install -r requirements/doc-spelling.txt
    - name: Run docs spelling
      run: |
        make doc-spelling
    - name: Prepare twine checker
   
   run: |
        pip install -U twine wheel
        python setup.py sdist bdist_wheel
    - name: Run twine checker
      run: |
        twine check dist/*